version: '3.1'

services:

  app:
    image: node:20
    restart: always
    depends_on:
      - mongo
    working_dir: /app/backend
    volumes:
      - .:/app
    ports:
      - 3000:3000
    networks:
      - mongodb_network
    environment:
      - MONGODB_PATH=mongodb://mongo:27017
      - BACKEND_URL=http://localhost:3000
    command: npm run prod-build-all

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - mongodb_network

networks:
  mongodb_network:
    driver: bridge
    name: mongo-network

